blank_issues_enabled: false
contact_links:
  - name: 提问
    url: https://github.com/PCL-Community/PCL2-Lobby-Guide/discussions/new?category=question
    about: 对某些内容不太理解，或有疑问
  - name: 讨论
    url: https://github.com/PCL-Community/PCL2-Lobby-Guide/discussions/new?category=general
    about: 讨论文档/服务端
